app:
  build: .
  environment:
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
loadbalancer:
  image: 'dockercloud/haproxy:latest'
  links:
    - app
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  ports:
    - 80:80
